 language: node_js
 node_js:
   - "0.10"

 branch:
  only:
    - master
    - /^3\.0$/
    - /^release-.*$/

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install

 script: grunt test-ci
